# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c389bdf67b082b1a3f9c770de9b9c335c38ead6eb60879dec996cdda50d03d3d81b889a7e20b861d7afeae3fc573a775b6494b80fefdfee3bba517f71b5fd5

test:
  secret_key_base: b1b06daa5a544d1437663d66da267b408cf9ca9b6f62955af0d79289b0b02b5290e37637018fe392ab106c8981a158496262d0ac16c9b52c57964063b7ca3f86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
